version: '3.8'
services:
  pin-server:
    build: .
    image: legalcontracts/pin-server:dev
    environment:
  # Set ADMIN_PRIVATE_KEY in your environment or secrets; do NOT store it in source
      - PIN_SERVER_PORTS=8080,3002
    ports:
      - "8080:8080"
      - "3002:3002"
    volumes:
      - ./store:/app/store
    restart: unless-stopped
