version: '3.8'
services:
  pin-server:
    build: .
    image: legalcontracts/pin-server:dev
    environment:
      - PIN_SERVER_API_KEY=dev-secret
      - ADMIN_PRIVATE_KEY=priv
      - PIN_SERVER_PORTS=8080,3002
    ports:
      - "8080:8080"
      - "3002:3002"
    volumes:
      - ./store:/app/store
    restart: unless-stopped
