# V7 AI Arbitrator Development Stack
version: '3.8'

services:
  # AI Arbitrator API
  arbitrator-api:
    build:
      context: .
      dockerfile: Dockerfile.arbitrator
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama
    networks:
      - arbitrator-net

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - arbitrator-net
    # Initialize with required models
    command: >
      sh -c "
        ollama serve &
        sleep 10 &&
        ollama pull llama3.1:8b &&
        ollama pull openhermes &&
        wait
      "

volumes:
  ollama_data:

networks:
  arbitrator-net:
    driver: bridge

# Usage:
# 1. docker-compose up -d
# 2. Wait for models to download (check: docker-compose logs ollama)
# 3. Test API: python test_arbitrator.py
# 4. API docs: http://localhost:8000/docs