name: IPFS Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Start go-ipfs via docker compose
        working-directory: ./tools/ipfs
        run: |
          docker compose up -d

      - name: Wait for IPFS API
        run: |
          for i in {1..30}; do
            if curl -sSf http://127.0.0.1:5001/api/v0/version >/dev/null 2>&1; then echo "ipfs api ready" && break; fi
            echo "waiting for ipfs..."; sleep 1;
          done

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Tear down go-ipfs
        if: always()
        working-directory: ./tools/ipfs
        run: docker compose down --remove-orphans
name: IPFS Integration

on:
  push:
    paths:
      - 'tools/ipfs/**'
  pull_request:
    paths:
      - 'tools/ipfs/**'

jobs:
  integration:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20-dind
        privileged: true
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Start docker compose for ipfs
        run: |
          cd tools/ipfs
          docker compose up -d
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd tools/ipfs
          npm ci
      - name: Run integration
        run: |
          cd tools/ipfs
          npm run integration
      - name: Tear down ipfs
        if: always()
        run: |
          cd tools/ipfs
          docker compose down --remove-orphans
